title: "Rではじめる生態学の統計処理"
summary: "生態学で必要となる統計処理をRで学ぶ"
topics: ["R", "Ecology", "Statistics"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_introduction
  - 02_one_sample
